<?php

$actions = [
    ['action' => 'AddAdExtensions', 'description' => 'Adds one or more ad extensions to an account\'s ad extension library.', 'request_Limits' => '1 AccountId,100 AdExtensions'],
    ['action' => 'AddAdGroupCriterions', 'description' => 'Adds one or more ad group criterions.', 'request_Limits' => '1 AccountId,1,000 AdGroupCriterions'],
    ['action' => 'AddAdGroups', 'description' => 'Adds new ad groups to a specified campaign.', 'request_Limits' => '1,000 AdGroups,1 CampaignId'],
    ['action' => 'AddAds', 'description' => 'Adds one or more ads to an ad group.', 'request_Limits' => '1 AdGroupId,50 Ads'],
    ['action' => 'AddAudiences', 'description' => 'Adds one or more audiences.', 'request_Limits' => '100 Audiences'],
    ['action' => 'AddBidStrategies', 'description' => 'Adds bid strategies to an account\'s portfolio bid strategy library.', 'request_Limits' => '100 BidStrategies'],
    ['action' => 'AddBudgets', 'description' => 'Adds new budgets to the account\'s shared budget library.', 'request_Limits' => '100 Budgets'],
    ['action' => 'AddCampaignConversionGoals', 'description' => 'Reserved.', 'request_Limits' => '0'],
    ['action' => 'AddCampaignCriterions', 'description' => 'Adds one or more campaign criterions that help determine whether ads in each campaign get served.', 'request_Limits' => '100 CampaignCriterions'],
    ['action' => 'AddCampaigns', 'description' => 'Adds one or more campaigns to the specified account.', 'request_Limits' => '1 AccountId,100 Campaigns'],
    ['action' => 'AddConversionGoals', 'description' => 'Adds new conversion goals to the account\'s shared conversion goal library.', 'request_Limits' => '100 ConversionGoals'],
    ['action' => 'AddExperiments', 'description' => 'Adds experiments and creates experiment campaigns based on existing campaigns in an account.', 'request_Limits' => '100 Experiments'],
    ['action' => 'AddImportJobs', 'description' => 'Creates a new import job.', 'request_Limits' => '1 ImportJobs'],
    ['action' => 'AddKeywords', 'description' => 'Adds one or more keywords to an ad group.', 'request_Limits' => '1 AdGroupId,1,000 Keywords'],
    ['action' => 'AddLabels', 'description' => 'Adds one or more labels to an account.', 'request_Limits' => '100 Labels'],
    ['action' => 'AddListItemsToSharedList', 'description' => 'Adds negative keywords to a negative keyword list, or negative sites to a website exclusion list.', 'request_Limits' => '1 SharedList,5,000 ListItems'],
    ['action' => 'AddMedia', 'description' => 'Adds the specified media to an account\'s media library.', 'request_Limits' => '1 AccountId,10 Media'],
    ['action' => 'AddNegativeKeywordsToEntities', 'description' => 'Adds negative keywords to the specified campaign or ad group.', 'request_Limits' => '1 EntityNegativeKeywords,Each EntityNegativeKeywordelement can contain up to 20,000 negative keywords.'],
    ['action' => 'AddSharedEntity', 'description' => 'Adds a negative keyword list to the ad account library, or adds a website exclusion list to the manager account (customer) library.', 'request_Limits' => '1 SharedEntity,5,000 ListItems'],
    ['action' => 'AddUetTags', 'description' => 'Adds new Universal Event Tracking (UET) tags that you can add to your website to allow Microsoft Advertising to collect actions people take on your website.', 'request_Limits' => '100 UetTags'],
    ['action' => 'AddVideos', 'description' => 'Adds one or more videos to an account.', 'request_Limits' => '100 Videos'],
    ['action' => 'AppealEditorialRejections', 'description' => 'Appeals ads or keywords that failed editorial review.', 'request_Limits' => '1,000 EntityIdToParentIdAssociations'],
    ['action' => 'ApplyOfflineConversionAdjustments', 'description' => 'Applies offline conversion adjustments.', 'request_Limits' => '1,000 OfflineConversionAdjustments'],
    ['action' => 'ApplyOfflineConversions', 'description' => 'Applies offline conversions for the account with Microsoft Click Id among other offline conversion data.', 'request_Limits' => '1,000 OfflineConversions'],
    ['action' => 'ApplyProductPartitionActions', 'description' => 'Applies an add, update, or delete action to each of the specified BiddableAdGroupCriterionor NegativeAdGroupCriterion, which each contain a ProductPartition.', 'request_Limits' => '5,000 CriterionActions'],
    ['action' => 'DeleteAdExtensions', 'description' => 'Deletes one or more ad extensions from the account\'s ad extension library.', 'request_Limits' => '1 AccountId,100 AdExtensionIds'],
    ['action' => 'DeleteAdExtensionsAssociations', 'description' => 'Removes the specified association from the respective campaigns or ad groups.', 'request_Limits' => '100 AdExtensionIdToEntityIdAssociations 1 AccountId'],
    ['action' => 'DeleteAdGroupCriterions', 'description' => 'Deletes the specified ad group criterions.', 'request_Limits' => '1 AccountId,1,000 AdGroupCriterionIds'],
    ['action' => 'DeleteAdGroups', 'description' => 'Deletes one or more ad groups from the specified campaign.', 'request_Limits' => '1,000 AdGroupIds,1 CampaignId'],
    ['action' => 'DeleteAds', 'description' => 'Deletes one or more ads from the specified ad group.', 'request_Limits' => '1 AdGroupId,50 AdIds'],
    ['action' => 'DeleteAudiences', 'description' => 'Deletes the specified audiences.', 'request_Limits' => '100 AudienceIds'],
    ['action' => 'DeleteBidStrategies', 'description' => 'Deletes bid strategies from an account\'s portfolio bid strategy library.', 'request_Limits' => '100 BidStrategyIds'],
    ['action' => 'DeleteBudgets', 'description' => 'Deletes budgets from the account\'s shared budget library.', 'request_Limits' => '100 BudgetIds'],
    ['action' => 'DeleteCampaignConversionGoals', 'description' => 'Reserved.', 'request_Limits' => '0'],
    ['action' => 'DeleteCampaignCriterions', 'description' => 'Deletes one or more campaign criterions.', 'request_Limits' => '100 CampaignCriterionIds'],
    ['action' => 'DeleteCampaigns', 'description' => 'Deletes one or more campaigns in a specified account.', 'request_Limits' => '1 AccountId,100 CampaignIds'],
    ['action' => 'DeleteExperiments', 'description' => 'Deletes one or more experiments.', 'request_Limits' => '100 ExperimentIds'],
    ['action' => 'DeleteImportJobs', 'description' => 'Deletes the import jobs.', 'request_Limits' => '1 ImportJobs'],
    ['action' => 'DeleteKeywords', 'description' => 'Deletes one or more keywords in a specified ad group.', 'request_Limits' => '1 AdGroupId,1,000 KeywordIds'],
    ['action' => 'DeleteLabelAssociations', 'description' => 'Deletes label associations.', 'request_Limits' => '100 LabelAssociations'],
    ['action' => 'DeleteLabels', 'description' => 'Deletes one or more labels from the account.', 'request_Limits' => '100 LabelIds'],
    ['action' => 'DeleteListItemsFromSharedList', 'description' => 'Deletes negative keywords from a negative keyword list, or negative sites from a website exclusion list.', 'request_Limits' => '1 SharedList,5,000 ListItemIds'],
    ['action' => 'DeleteMedia', 'description' => 'Deletes the specified media from an account\'s media library.', 'request_Limits' => '1 AccountId,100MediaIds'],
    ['action' => 'DeleteNegativeKeywordsFromEntities', 'description' => 'Deletes negative keywords from the specified campaign or ad group.', 'request_Limits' => '1 EntityNegativeKeywords,Each EntityNegativeKeywordelement can contain up to 20,000 negative keywords.'],
    ['action' => 'DeleteSharedEntities', 'description' => 'Deletes negative keyword lists from the ad account library, or deletes website exclusion lists from the manager account (customer) library.', 'request_Limits' => '20 SharedEntities'],
    ['action' => 'DeleteSharedEntityAssociations', 'description' => 'Deletes the negative keyword list to campaign associations, or website exclusion list to ad account associations.', 'request_Limits' => '10,000 Associations'],
    ['action' => 'DeleteVideos', 'description' => 'Deletes one or more videos from the account.', 'request_Limits' => '100 VideoIds'],
    ['action' => 'GetAccountMigrationStatuses', 'description' => 'Gets the migration status info for the specified accounts.', 'request_Limits' => '1,000 AccountIds'],
    ['action' => 'GetAccountProperties', 'description' => 'Gets account level properties by name.', 'request_Limits' => 'Not applicable'],
    ['action' => 'GetAdExtensionIdsByAccountId', 'description' => 'Gets the ad extensions from the account\'s ad extension library.', 'request_Limits' => '1 AccountId'],
    ['action' => 'GetAdExtensionsAssociations', 'description' => 'Gets the respective ad extension associations by the specified campaign and ad group identifiers.', 'request_Limits' => '1 AccountId,100 EntityIds'],
    ['action' => 'GetAdExtensionsByIds', 'description' => 'Gets the specified ad extensions from the account\'s ad extension library.', 'request_Limits' => '1 AccountId,100 AdExtensionIds'],
    ['action' => 'GetAdExtensionsEditorialReasons', 'description' => 'Gets reasons for ad extension editorial issues.', 'request_Limits' => '1 AccountId,100 AdExtensionIdToEntityIdAssociations'],
    ['action' => 'GetAdGroupCriterionsByIds', 'description' => 'Gets ad group criterions by identifiers and types.', 'request_Limits' => '1 AccountId,1,000 AdGroupCriterionIds'],
    ['action' => 'GetAdGroupsByCampaignId', 'description' => 'Gets the ad groups within the specified campaign.', 'request_Limits' => '1 CampaignId'],
    ['action' => 'GetAdGroupsByIds', 'description' => 'Gets the specified ad groups within the specified campaign.', 'request_Limits' => '1,000 AdGroupIds,1 CampaignId'],
    ['action' => 'GetAdsByAdGroupId', 'description' => 'Retrieves the ads within an ad group.', 'request_Limits' => '1 AdGroupId'],
    ['action' => 'GetAdsByEditorialStatus', 'description' => 'Retrieves the ads that belong to the specified ad group and have the specified editorial review status.', 'request_Limits' => '1 AdGroupId'],
    ['action' => 'GetAdsByIds', 'description' => 'Retrieves the specified ads from the specified ad group.', 'request_Limits' => '1 AdGroupId,20 AdIds'],
    ['action' => 'GetAudiencesByIds', 'description' => 'Retrieves the specified audiences from the specified account.', 'request_Limits' => '100 AudienceIds'],
    ['action' => 'GetBidStrategiesByIds', 'description' => 'Gets bid strategies in an account\'s portfolio bid strategy library.', 'request_Limits' => '100 BidStrategyIds'],
    ['action' => 'GetBMCStoresByCustomerId', 'description' => 'Gets the Microsoft Merchant Center stores for the specified customer.', 'request_Limits' => 'Not applicable.'],
    ['action' => 'GetBSCCountries', 'description' => 'Gets the list of supported sales country codes for Microsoft Shopping Campaigns.', 'request_Limits' => 'Not applicable.'],
    ['action' => 'GetBudgetsByIds', 'description' => 'Gets the specified budgets from the account\'s shared budget library.', 'request_Limits' => '100 BudgetIds'],
    ['action' => 'GetCampaignCriterionsByIds', 'description' => 'Gets the specified campaign criterions.', 'request_Limits' => '100 CampaignCriterionIds,1 CampaignId'],
    ['action' => 'GetCampaignIdsByBidStrategyIds', 'description' => 'Gets the campaign identifiers that are associated with the specified portfolio bid strategies.', 'request_Limits' => '100 BidStrategyIds'],
    ['action' => 'GetCampaignIdsByBudgetIds', 'description' => 'Gets the campaign identifiers that share each specified budget.', 'request_Limits' => '100 BudgetIds'],
    ['action' => 'GetCampaignsByAccountId', 'description' => 'Gets the campaigns within an account.', 'request_Limits' => '1 AccountId'],
    ['action' => 'GetCampaignsByIds', 'description' => 'Gets the specified campaigns within an account.', 'request_Limits' => '1 AccountId,100 CampaignIds'],
    ['action' => 'GetConversionGoalsByIds', 'description' => 'Gets the specified conversion goals.', 'request_Limits' => '100 ConversionGoalIds'],
    ['action' => 'GetConversionGoalsByTagIds', 'description' => 'Gets the conversion goals that use the specified UET tags.', 'request_Limits' => '100 TagIds'],
    ['action' => 'GetEditorialReasonsByIds', 'description' => 'Gets the reasons why the specified entities failed editorial review and whether the issue is appealable.', 'request_Limits' => '1 AccountId,1,000 EntityIdToParentIdAssociations'],
    ['action' => 'GetExperimentsByIds', 'description' => 'Gets experiments by experiment identifiers.', 'request_Limits' => '5,000 ExperimentIds'],
    ['action' => 'GetFileImportUploadUrl', 'description' => 'GetFileImportUploadUrl is reserved for future use.', 'request_Limits' => 'N/A.'],
    ['action' => 'GetGeoLocationsFileUrl', 'description' => 'Gets a temporary URL that you can use to download a file that contains identifiers for the geographical locations that you can target or exclude.', 'request_Limits' => 'Not applicable.'],
    ['action' => 'GetImportEntityIdsMapping', 'description' => 'Gets mappings of your source entity IDs to Microsoft Advertising entity IDs.', 'request_Limits' => '100 SourceEntityIds'],
    ['action' => 'GetImportJobsByIds', 'description' => 'Gets import jobs by their type and identifiers.', 'request_Limits' => '100 ImportJobIds'],
    ['action' => 'GetImportResults', 'description' => 'Gets results for import jobs completed within the last 90 days.', 'request_Limits' => '100 ImportJobIds'],
    ['action' => 'GetKeywordsByAdGroupId', 'description' => 'Gets the keywords within an ad group.', 'request_Limits' => '1 AdGroupId'],
    ['action' => 'GetKeywordsByEditorialStatus', 'description' => 'Retrieves the keywords with the specified editorial review status.', 'request_Limits' => '1 AdGroupId'],
    ['action' => 'GetKeywordsByIds', 'description' => 'Retrieves the specified keywords.', 'request_Limits' => '1 AdGroupId,1,000 KeywordIds'],
    ['action' => 'GetLabelAssociationsByEntityIds', 'description' => 'Gets label associations by entity identifiers.', 'request_Limits' => '100 EntityIds'],
    ['action' => 'GetLabelAssociationsByLabelIds', 'description' => 'Gets label associations by label identifiers.', 'request_Limits' => '1 LabelIds'],
    ['action' => 'GetLabelsByIds', 'description' => 'Gets labels by label identifiers.', 'request_Limits' => '1,000 LabelIds'],
    ['action' => 'GetListItemsBySharedList', 'description' => 'Gets the negative keywords of a negative keyword list, or negative sites of a website exclusion list.', 'request_Limits' => '1 SharedList'],
    ['action' => 'GetMediaAssociations', 'description' => 'Gets the media associations of the specified entity type from an account\'s media library.', 'request_Limits' => '1 AccountId,100 MediaIds'],
    ['action' => 'GetMediaMetaDataByAccountId', 'description' => 'Gets the media meta data of the specified entity type from an account\'s media library.', 'request_Limits' => 'Not applicable.'],
    ['action' => 'GetMediaMetaDataByIds', 'description' => 'Gets the specified media meta data from an account\'s media library.', 'request_Limits' => '100 MediaIds'],
    ['action' => 'GetNegativeKeywordsByEntityIds', 'description' => 'Gets the negative keywords that are assigned directly to campaigns or ad groups.', 'request_Limits' => '1 ParentEntityId,1 EntityIds'],
    ['action' => 'GetNegativeSitesByAdGroupIds', 'description' => 'Gets the negative sites URLs that are assigned directly to ad groups.', 'request_Limits' => '15 AdGroupIds,1 CampaignId'],
    ['action' => 'GetNegativeSitesByCampaignIds', 'description' => 'Gets the negative site URLs that are assigned directly to campaigns.', 'request_Limits' => '1 AccountId,15 CampaignIds'],
    ['action' => 'GetProfileDataFileUrl', 'description' => 'Gets a temporary URL that you can use to download industry or job function profile data.', 'request_Limits' => '1 ProfileType'],
    ['action' => 'GetSharedEntities', 'description' => 'Gets negative keyword lists or website exclusion lists.', 'request_Limits' => 'Not applicable.'],
    ['action' => 'GetSharedEntitiesByAccountId', 'description' => 'Gets negative keyword lists.', 'request_Limits' => 'Not applicable.'],
    ['action' => 'GetSharedEntityAssociationsByEntityIds', 'description' => 'Gets the negative keyword list to campaign associations by campaign IDs, or website exclusion list to ad account associations by ad account IDs.', 'request_Limits' => '100 EntityIds'],
    ['action' => 'GetSharedEntityAssociationsBySharedEntityIds', 'description' => 'Gets the negative keyword list to campaign associations by negative keyword list IDs, or website exclusion list to ad account associations by website exclusion list IDs.', 'request_Limits' => '1 SharedEntityIds'],
    ['action' => 'GetUetTagsByIds', 'description' => 'Gets the specified Universal Event Tracking (UET) tags.', 'request_Limits' => '100 TagIds'],
    ['action' => 'GetVideosByIds', 'description' => 'Gets videos by video identifiers.', 'request_Limits' => '1,000 VideoIds'],
    ['action' => 'SearchCompanies', 'description' => 'Search for profile data by company name.', 'request_Limits' => '1 CompanyNameFilter'],
    ['action' => 'SetAccountProperties', 'description' => 'Sets account level properties by name.', 'request_Limits' => 'Not applicable'],
    ['action' => 'SetAdExtensionsAssociations', 'description' => 'Associates the specified ad extensions with the respective campaigns or ad groups.', 'request_Limits' => '1 AccountId,100 AdExtensionIdToEntityIdAssociations'],
    ['action' => 'SetLabelAssociations', 'description' => 'Sets label associations.', 'request_Limits' => '100 LabelAssociations'],
    ['action' => 'SetNegativeSitesToAdGroups', 'description' => 'Sets the negative site URLs directly to ad groups.', 'request_Limits' => '5,000 AdGroupNegativeSites,1 CampaignId'],
    ['action' => 'SetNegativeSitesToCampaigns', 'description' => 'Sets the negative site URLs directly to campaigns.', 'request_Limits' => '1 AccountId,5,000 CampaignNegativeSites'],
    ['action' => 'SetSharedEntityAssociations', 'description' => 'Sets the negative keyword list to campaign associations, or website exclusion list to ad account associations.', 'request_Limits' => '10,000 Associations'],
    ['action' => 'UpdateAdExtensions', 'description' => 'Updates one or more ad extensions within an account\'s ad extension library.', 'request_Limits' => '1 AccountId,100 AdExtensions'],
    ['action' => 'UpdateAdGroupCriterions', 'description' => 'Updates one or more ad group criterions.', 'request_Limits' => '1 AccountId,1 CampaignId'],
    ['action' => 'UpdateAdGroups', 'description' => 'Updates the specified ad groups in a campaign.', 'request_Limits' => '1,000 AdGroups,1 CampaignId'],
    ['action' => 'UpdateAds', 'description' => 'Updates the specified ads within an ad group.', 'request_Limits' => '1 AdGroupId,50 Ads'],
    ['action' => 'UpdateAudiences', 'description' => 'Updates the specified audiences.', 'request_Limits' => '100 Audiences'],
    ['action' => 'UpdateBidStrategies', 'description' => 'Updates bid strategies in an account\'s portfolio bid strategy library.', 'request_Limits' => '100 BidStrategies'],
    ['action' => 'UpdateBudgets', 'description' => 'Updates the specified budgets in the account\'s shared budget library.', 'request_Limits' => '100 Budgets'],
    ['action' => 'UpdateCampaignCriterions', 'description' => 'Updates one or more campaign criterions.', 'request_Limits' => '100 CampaignCriterions'],
    ['action' => 'UpdateCampaigns', 'description' => 'Updates specified campaigns in a specified account.', 'request_Limits' => '1 AccountId,100 Campaigns'],
    ['action' => 'UpdateConversionGoals', 'description' => 'Updates conversion goals within the account\'s shared conversion goal library.', 'request_Limits' => '100 ConversionGoals'],
    ['action' => 'UpdateExperiments', 'description' => 'Updates the specified experiments.', 'request_Limits' => '100 Experiments'],
    ['action' => 'UpdateImportJobs', 'description' => 'Replaces the specified import jobs with new import jobs.', 'request_Limits' => '1 ImportJobs'],
    ['action' => 'UpdateKeywords', 'description' => 'Updates the keywords within a specified ad group.', 'request_Limits' => '1 AdGroupId,1,000 Keywords'],
    ['action' => 'UpdateLabels', 'description' => 'Updates the labels within the account.', 'request_Limits' => '100 Labels'],
    ['action' => 'UpdateSharedEntities', 'description' => 'Updates the negative keyword lists or website exclusion lists.', 'request_Limits' => '20 SharedEntities'],
    ['action' => 'UpdateUetTags', 'description' => 'Updates the specified Universal Event Tracking (UET) tags.', 'request_Limits' => '100 UetTags'],
    ['action' => 'UpdateVideos', 'description' => 'Updates the videos within the account.', 'request_Limits' => '100 Videos'],
];

$my_array = array("Dog","Cat","Horse");

